buildscript {
  dependencies {
    classpath 'com.android.tools.build:gradle:3.6.3'
  }
}

apply plugin: 'com.android.library'

android {
  compileSdkVersion 30

  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }

  lintOptions {
    textOutput 'stdout'
    textReport true
    lintConfig file('lint.xml')
  }

  defaultConfig {
    minSdkVersion 21
  }
}

dependencies {
  api project(':picasso')
  api dep.pollexor
  compileOnly dep.supportAnnotations
  testImplementation dep.junit
  testImplementation dep.robolectric
  testImplementation dep.truth
  testImplementation dep.pollexor
}