buildscript {
  repositories {
    mavenCentral()
    jcenter()
    google()
  }
  dependencies {
    classpath 'com.android.tools.build:gradle:3.6.3'
  }
}

apply plugin: 'com.android.library'

android {
  compileSdkVersion 30

  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }

  lintOptions {
    textOutput 'stdout'
    textReport true
    lintConfig file('lint.xml')
  }

  defaultConfig {
    minSdkVersion 21

    consumerProguardFiles 'consumer-proguard-rules.txt'
  }
}

dependencies {
  api "com.squareup.okhttp3:okhttp:$okhttpVersion"
  compileOnly "androidx.annotation:annotation:1.0.0-beta01"
  testImplementation "junit:junit:$junitVersion"
  testImplementation "com.google.truth:truth:$truthVersion"
  testImplementation "androidx.legacy:legacy-support-v4:1.0.0-beta01"
  testImplementation "org.robolectric:robolectric:$robolectricVersion"
  testImplementation "org.mockito:mockito-core:$mockitoVersion"
  testImplementation "com.squareup.okhttp3:mockwebserver:$okhttpVersion"
}

// TODO upgrade picasso and use latest gradle configurations
// TODO https://www.pivotaltracker.com/story/show/179398618
//apply from: rootProject.file('gradle/gradle-mvn-push.gradle')
