plugins {
    alias libs.plugins.android.library
}

android {
    namespace 'com.squareup.picasso'

    compileSdk libs.versions.android.sdk.compile.get().toInteger()
    defaultConfig {
        minSdkVersion libs.versions.android.sdk.min.get()
        targetSdkVersion libs.versions.android.sdk.target.get()
        consumerProguardFiles 'consumer-proguard-rules.txt'
    }

    lintOptions {
        textOutput 'stdout'
        textReport true
        lintConfig file('lint.xml')
    }
}

dependencies {
    api libs.square.okhttp
    compileOnly libs.androidx.annotation
}
