buildscript {
  dependencies {
    classpath 'com.android.tools.build:gradle:3.6.3'
  }
}

apply plugin: 'com.android.application'

dependencies {
  implementation dep.supportV4
  compileOnly dep.supportAnnotations
  implementation project(':picasso')
}

android {
  compileSdkVersion 32

  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }

  lintOptions {
    lintConfig file('lint.xml')
    textOutput 'stdout'
    textReport true

    // https://github.com/square/okhttp/issues/896
    ignore 'InvalidPackage'
  }

  defaultConfig {
    minSdkVersion 21
    targetSdkVersion 31
    applicationId 'com.example.picasso'

    versionCode 1
    versionName '1.0'
  }

  buildTypes {
    debug {
      applicationIdSuffix '.development'
    }
  }
}
